image: node:18.20.8-alpine3.21
create-pages:
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - mv src public
    - mv nodejs/* .
    - npm install
    - npm run build
    - for file in $(ls); do if test "$file" != "public"; then rm -rf "$file"; done
  only:
    - online-gitlab