image: node:18.20.8-alpine3.21

stages:
  - build
  - deploy

cache:
  paths:
    - public/

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "online-gitlab"'

default:
  before_script:
    - echo "Starting job - '$CI_JOB_NAME' ($CI_JOB_STAGE - $CI_JOB_ID),"
    - echo "At - '$(date)'."
    - echo "Available files:"
    - ls -R ./public
  after_script:
    - echo "Finishing job - '$CI_JOB_NAME' ($CI_JOB_STAGE - $CI_JOB_ID),"
    - echo "At - '$(date)'."
    - echo "Available files:"
    - ls -R ./public

# it had been based in
# the `Dockerfile`
process-source-code:
  stage: build
  script:
    - mv src public
    - mv .github/404.html public
    - mv nodejs/* .
    - npm install
    - npm run build


publish-content:
  stage: deploy
  script:
    - rm -rf $(ls | grep -v 'public')