#!/usr/bin/env bash

# GLOBAL

declare -r  ARG_function="$1"
declare -ra ARG_arguments=(${@:2})

declare -ri TRUE=0
declare -ri FALSE=1

declare -r CSS_CORE="./style/css/core.css"
declare -r DIR_CSS="./style/css/"
declare -r DIR_SCSS="./style/scss/"

declare -ra PROTECT_CSS_FILE=()

is_dir(){
	test -d "$1" && return $TRUE
	return $FALSE
}

is_file(){
	test -f "$1" && return $TRUE
	return $FALSE
}

check_not_found(){
	test $1 -ne $TRUE && echo "[ Nothing was found ]"
}


# BUILD

build_scss_to_css(){
	is_dir "$DIR_CSS" || mkdir "$DIR_CSS"

	if ! is_file "$CSS_CORE"; then
		echo "'$CSS_CORE' not found"
		return
	fi

	npx sass "$DIR_SCSS:$DIR_CSS"

	local -r cleaned=$(npx cleancss "$CSS_CORE")
	echo "$cleaned" > "$CSS_CORE"

	echo '/*# sourceMappingURL=core.css.map */' >> "$CSS_CORE"
}


# CLEAR

clear_css_from_scss(){
	for file in $(ls "$DIR_CSS"); do
		for ig in ${PROTECT_CSS_FILES[@]}; do
			test "$file" = "$ig" && continue 2
		done

		rm -r "$DIR_CSS/$file"
	done
}


# OTHER

help_npm_scripts(){
	echo -e 'css      build CSS files, from ./style/scss, in ./style/css.
nocss    delete CSS files, from ./style/css.
uncss    search unused classes (in HTML and CSS) and display them.
help     display this help message.
dev      run the page on localhost at port 7777, if ./index.html exist.
grep     search a Perl RegExp pattern in all files.'
}

run_localhost_server(){
	local -r NO_CACHE="-c-1"
	local -r PORT="7777"

	npx http-server "$NO_CACHE" -p "$PORT"
}

git_grep_from_root(){
	git grep -Pn "${ARG_arguments[@]}" -- ./

	check_not_found $?
}

find_unused_css_classes(){
	node ./uncss.js | git grep -Pnf -

	check_not_found $?
}


# RUN

if ! type "$ARG_function" &> /dev/null; then
	echo "'$ARG_function' not exist!"
else
	eval "$ARG_function"
fi

echo ""
exit 0
