#!/usr/bin/env bash


# GLOBAL

declare -r ARG_function="$1"

declare -ri TRUE=0
declare -ri FALSE=1

declare -r  DIR_CSS="./style/css/"
declare -r  DIR_SCSS="./style/scss/"
declare -ra PROTECT_CSS_FILE=()

is_dir(){
	test -d "$1" && return $TRUE
	return $FALSE
}


# BUILD

build_scss_to_css(){
	is_dir "$DIR_CSS" || mkdir "$DIR_CSS"

	npx sass "$DIR_SCSS:$DIR_CSS"
}


# CLEAR

clear_css_from_scss(){
	for file in $(ls "$DIR_CSS"); do
		for ig in ${PROTECT_CSS_FILES[@]}; do
			test "$file" = "$ig" && continue 2
		done

		rm -r "$DIR_CSS/$file"
	done
}


# OTHER

help_npm_scripts(){
	echo -e 'css      build CSS files, from ./style/scss, in ./style/css.
nocss    delete CSS files, from ./style/css.
help     display this help message.
dev      run the page on localhost at port 7777, if ./index.html exist.'
}

run_localhost_server(){
	local -r NO_CACHE="-c-1"
	local -r PORT="7777"

	npx http-server "$NO_CACHE" -p "$PORT"
}


# RUN

if ! type "$ARG_function" &> /dev/null; then
	echo "'$ARG_function' not exist!"
else
	eval "$ARG_function"
fi
