#!/usr/bin/env bash

# MIT License
#
# Copyright (c) 2025 DuckAfire <https://duckafire.gitlab.io>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# ./run-docker-container [container-hash]


declare -r CONTAINER_NAME="nest"
declare -r CONTAINER_PORT="8080:8080"


docker kill nest &> /dev/null
docker build "$(realpath "$(dirname "$0")")"
docker images | head -n 2


declare input

if [[ $# -eq 0 ]]
then
	printf '\n\e[32mContainer hash:\e[0m '
	read input
	echo ""
else
	input="$1"
fi


docker run --rm --name "$CONTAINER_NAME" --publish "$CONTAINER_PORT" --detach "$input"

exit 0
