#!/usr/bin/env bash

docker kill nest &> /dev/null

docker build "$(realpath "$(dirname "$0")")"
docker images

declare input

if [[ $# -eq 0 ]]
then
	printf '\n\e[32mContainer hash:\e[0m '
	read input
	echo ""
else
	input="$1"
fi

docker run --rm --name nest --publish 8080:8080 --detach "$input"

exit 0
